import 'package:flutter/animation.dart';

const colorButton = Color(0xFF3D40C6);
const colorFacebook = Color(0xFF4666D5);
const colorTextGmail = Color(0xff4e4a66);
const colorGrayScaleLabel = Color(0xFF6E7191);
const colorTextError = Color(0xFFFF4C4D);
const colorLabalTextFiled = Color(0xFF262338);
const colorScafold = Color(0xFFF7F7FC);
const colorTextRegister = Color(0xFF00C7FF);
const colorSuccess = Color(0xFFE5FFF2);
const colorTextBlueDart = Color(0xFF007099);
const colorGreenMedium = Color(0xFF00CC67);
const colorSuccessDark = Color(0xFF00994D);
const colorLight = Color(0xFFEEE5FE);
const colorGrayScale = Color(0xFFEFF0F6);
const colorToggle = Color(0xFFD9DBE9);
const colorGrayScaleBOdy = Color(0xFF4E4B66);
const colorPinkLight = Color(0xFFF7F2FF);
const colorGradientBlue = Color(0xFFE3F7FF);
const colorTextAuthor = Color(0xFFA0A3BD);
const colorGradientPink = Color(0xFFFFF8F2);
const colorBackgr = Color(0xFFE5E5E5);
const colorBeginGradient = Color.fromRGBO(5, 5, 5, 0);
const colorEndGradient = Color.fromRGBO(2, 2, 2, 0.5);
const colorBeginGradientSplash = Color.fromRGBO(95, 46, 243, 1);
const colorEndGradientSplash = Color.fromRGBO(227, 89, 249, 1);
